name: Build Assets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run a script to process assets
        run: |
          echo "Aquí ejecutas tus scripts para generar assets"
          # Ejemplo: python scripts/build_spritesheet.py

      - name: Upload assets as artifact
        uses: actions/upload-artifact@v4
        with:
          name: LeatherAssets
          path: |
            assets/xml/default.xml
            assets/images/default.png
